### PR TITLE
Added operator logos

### PR DESCRIPTION
**Pull request by Pixtxa**
## Credits
Pixtxa

## Technical info

untested

## Other requests

It's pixeled by hand and I don't have the equipment to test it, but it would be nice to see the logos in the field

### CODE REVIEW

**Comment by Manawyrm** [comment]
😸 🥳
Awesome, these look fantastic and seem to be in right format! Thank you, I'll add them right away!

**Comment by Manawyrm** [comment]
(will probably clean the names up a bit)

**Comment by Pixtxa** [comment]
Maybe also the order could be cleaned up a bit, so blank and censor bar, sunrise and sunset and the different versions of PIXELS! are together. I've also an inverted HACKERTOOL in the next PR, because there were enough free pixels unused

**Comment by Manawyrm** [comment]
yeah, the order is currently by-insert-order in the database, right from the filesystem... That's not very ideal 😥 😄

**Pull request merged**
